-- Add rating column to comments table
ALTER TABLE public.comments ADD COLUMN comment_rating INTEGER DEFAULT 0;

-- Create comment_likes table for tracking who liked which comments
CREATE TABLE public.comment_likes (
    like_id INT GENERATED BY DEFAULT AS IDENTITY,
    comment_id INT NOT NULL,
    account_id INT NOT NULL,
    like_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comment_likes_pk PRIMARY KEY (like_id),
    CONSTRAINT comment_likes_comment_fk FOREIGN KEY (comment_id)
        REFERENCES public.comments (comment_id)
        ON DELETE CASCADE,
    CONSTRAINT comment_likes_account_fk FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON DELETE CASCADE,
    CONSTRAINT unique_comment_like UNIQUE (comment_id, account_id)
);